### ISSUE TITLE
SDK not compatible with Swift 4.1

### ISSUE THREAD

**Issue by bverp** [Estimote/iOS-Proximity-SDK#7] opened 2018-03-11 22:22 UTC
When using Xcode 9.3 (beta 4) building generates the error "The following binaries use incompatible versions of Swift" as it seems that the SDK is not compatible with Swift 4.1.

**Comment by neuronaut** [comment] 2018-03-30 21:17
I just upgraded to the release of Xcode 9.3 and I'm getting the same issue. Could someone at Estimate please compile this library using Xcode 9.3 to make it compatible?

**Comment by hishma** [comment] 2018-03-30 22:49
+1

**Comment by naruto9lol** [comment] 2018-04-01 01:33
same problem here

**Comment by fonesti** [comment] 2018-04-04 09:38
+1

**Comment by troya2** [comment] 2018-04-06 04:24
+1

**Comment by croustibat** [comment] 2018-04-06 14:39
+1
i've got this strange error : 
`dyld: Symbol not found: __T0SayxGs9DecodableslWP`

**Comment by croustibat** [comment] 2018-04-07 14:51
Yes ! it's working now ! i can compile an run my app.
Thank you @luki2505 to point out the post on the forum !

**Comment by Tibb** [comment] 2018-04-09 14:46
Confirmed! Thanks @luki2505 this version works 💯
 
@heypiotr @airalex thanks a lot for this bundled version! Do you consider to push a new release and make it available through CocoaPods soon?

**Comment by bartlomiejolma** [comment] 2018-04-10 14:40
@Tibb @croustibat @luki2505 @troya2 @fonesti @naruto9lol @hishma @neuronaut @JacobSyndeo @bverp 

Thank you all for reporting this issue. Yes, proper, new release will be added (and CocaPods update) soon - we are currently working on it right now.

**Comment by bartlomiejolma** [comment] 2018-04-12 06:33
The latest release (version 0.12.0) is compatible with Swift 4.1.

I am closing this issue.

**Closed by bartlomiejolma** 2018-04-12 06:33 UTC

**Comment by MatthewGerber** [comment] 2018-04-19 11:34
@bartlomiejolma I believe the Xamarin Bindings also need to be updated to 0.12.0 in order to be compatible with Swift 4.1. In addition to updating, it looks like the `EstimoteBluetoothScanning` framework needs to be added to the bindings projects (also mentioned in the issue). Can you take a look [here](https://github.com/Estimote/Xamarin-Bindings/issues/4) and let me know when this might be fixed? It's currently blocking a release.

Piotr has been maintaining the bindings, but it looks like he's become inactive on GitHub. Is he still the maintainer?
